version: '3.8'

services:
  backend:
    build:
      context: ../backend
      dockerfile: ../docker/backend.Dockerfile
    ports:
      - '5001:5001'
    env_file:
      - ../backend/.env
    volumes:
      - ../backend/uploads:/app/uploads
    depends_on:
      - mongo
    restart: unless-stopped

  frontend:
    build:
      context: ../frontend
      dockerfile: ../docker/frontend.Dockerfile
    ports:
      - '3000:80'
    depends_on:
      - backend
    restart: unless-stopped

  mongo:
    image: mongo:7
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

volumes:
  mongo_data:
